// Seed data for SPotion research system
const DEFAULT_PAPERS = [
  {
    id: "paper-root",
    title: "Self-Supervised Representation Learning from Arbitrary Scenarios",
    category: "Foundations",
    summary: "Current self-supervised methods can primarily be categorized into contrastive learning and masked image modeling. Extensive studies have demonstrated that combining these two approaches can achieve state-of-the-art performance. However, these methods essentially reinforce the global consistency of contrastive learning without taking into account the conflicts between these two approaches, which hinders their generalizability to arbitrary scenarios. In this paper, we theoretically prove that MAE serves as a patch-level contrastive learning, where each patch within an image is considered as a distinct category. This presents a significant conflict with global-level contrastive learning, which treats all patches in an image as an identical category. To address this conflict, this work abandons the non-generalizable global-level constraints and proposes explicit patch-level contrastive learning as a solution. Specifically, this work employs the encoder of MAE to generate dual-branch features, which then perform patch-level learning through a decoder. In contrast to global-level data augmentation in contrastive learning, our approach leverages patch-level feature augmentation to mitigate interference from global-level learning. Consequently, our approach can learn heterogeneous representations from a single image while avoiding the conflicts encountered by previous methods. Massive experiments affirm the potential of our method for learning from arbitrary scenarios.",
    link: "https://ieeexplore.ieee.org/document/10658461",
    x: 900,
    y: 650,
    color: "#1f4ed8",
    year: 2020,
    authors: "Shikun Zhang, Xiaohua Zhai, et al.",
    venue: "CACM / Meta AI",
    status: "Done",
    notes: "# Self-Supervised Learning Foundations\n\nSelf-supervised learning (SSL) is the paradigm of training a model on a pretext task where the targets are generated automatically from the data. This allows using massive datasets without requiring human annotation.\n\n### Key Concepts\n- **Joint Embedding Architectures**: Map inputs to representations without generating pixels directly.\n- **Contrastive Learning**: Pull representations of similar views together while pushing dissimilar views apart.\n- **Non-contrastive/Regularized Methods**: Avoid collapse using variance/covariance constraints (e.g., VICReg, Barlow Twins).",
    comments: []
  },
  {
    id: "paper-1",
    title: "Recent Advancements in Self-Supervised Paradigms for Visual Feature Representation",
    category: "Survey",
    summary: "We witnessed a massive growth in the supervised learning paradigm in the past decade. Supervised learning requires a large amount of labeled data to reach state-of-the-art performance. However, labeling the samples requires a lot of human annotation. To avoid the cost of labeling data, self-supervised methods were proposed to make use of largely available unlabeled data. This study conducts a comprehensive and insightful survey and analysis of recent developments in the self-supervised paradigm for feature representation. In this paper, we investigate the factors affecting the usefulness of self-supervision under different settings. We present some of the key insights concerning two different approaches in self-supervision, generative and contrastive methods. We also investigate the limitations of supervised adversarial training and how self-supervision can help overcome those limitations. We then move on to discuss the limitations and challenges in effectively using self-supervision for visual tasks. Finally, we highlight some open problems and point out future research directions.",
    link: "https://arxiv.org/pdf/2111.02042",
    x: 250,
    y: 180,
    color: "#7c3aed",
    year: 2021,
    authors: "P. Gu, et al.",
    venue: "arXiv (2111)",
    status: "Reading",
    notes: "# Recent Advancements in SSL Paradigms\n\nThis survey paper organizes SSL methods into contrastive, generative, and predictive approaches. It provides a comprehensive analysis of taxonomy and performance benchmarks.",
    comments: []
  },
  {
    id: "paper-2",
    title: "A Survey on Self-supervised Learning: Algorithms, Applications, and Future Trends",
    category: "Survey",
    summary: "Deep supervised learning algorithms typically require a large volume of labeled data to achieve satisfactory performance. However, the process of collecting and labeling such data can be expensive and time-consuming. Self-supervised learning (SSL), a subset of unsupervised learning, aims to learn discriminative features from unlabeled data without relying on human-annotated labels. SSL has garnered significant attention recently, leading to the development of numerous related algorithms. However, there is a dearth of comprehensive studies that elucidate the connections and evolution of different SSL variants. This paper presents a review of diverse SSL methods, encompassing algorithmic aspects, application domains, three key trends, and open research questions. Firstly, we provide a detailed introduction to the motivations behind most SSL algorithms and compare their commonalities and differences. Secondly, we explore representative applications of SSL in domains such as image processing, computer vision, and natural language processing. Lastly, we discuss the three primary trends observed in SSL research and highlight the open questions that remain. A curated collection of valuable resources can be accessed at this https URL.",
    link: "https://arxiv.org/pdf/2301.05712",
    x: 250,
    y: 360,
    color: "#7c3aed",
    year: 2024,
    authors: "S. Liu, T. Wang, et al.",
    venue: "arXiv (2408)",
    status: "Reading",
    notes: "# SSL: Algorithms, Applications & Future Trends\n\nExcellent reading for understanding current industry applications (autonomous driving, healthcare, robotics) and challenges like multimodal alignment.",
    comments: []
  },
  {
    id: "paper-3",
    title: "Self-Supervised Learning from Images with a Joint-Embedding Predictive Architecture",
    category: "Foundations",
    summary: "This paper demonstrates an approach for learning highly semantic image representations without relying on hand-crafted data-augmentations. We introduce the Image-based Joint-Embedding Predictive Architecture (I-JEPA), a non-generative approach for self-supervised learning from images. The idea behind I-JEPA is simple: from a single context block, predict the representations of various target blocks in the same image. A core design choice to guide I-JEPA towards producing semantic representations is the masking strategy; specifically, it is crucial to (a) sample target blocks with sufficiently large scale (semantic), and to (b) use a sufficiently informative (spatially distributed) context block. Empirically, when combined with Vision Transformers, we find I-JEPA to be highly scalable. For instance, we train a ViT-Huge/14 on ImageNet using 16 A100 GPUs in under 72 hours to achieve strong downstream performance across a wide range of tasks, from linear classification to object counting and depth prediction.",
    link: "https://arxiv.org/pdf/2301.08243.pdf",
    x: 250,
    y: 540,
    color: "#2563eb",
    year: 2023,
    authors: "S. Robertson, et al.",
    venue: "arXiv / Meta AI",
    status: "Reading",
    notes: "# Joint-Embedding Predictive Architecture (JEPA)\n\nJEPA avoids predicting raw pixel content (which contains too much noise/unpredictable detail) and instead predicts representations in a joint-embedding space.\n\n### Advantages:\n1. Less computationally expensive than autoencoders.\n2. Captures semantic relationships better.\n3. Robust to pixel-level variations.",
    comments: []
  },
  {
    id: "paper-5",
    title: "Self-supervised Domain Adaptation for Computer Vision Tasks",
    category: "Foundations",
    summary: "Cross-domain representation learning techniques utilizing self-supervision to align source and target distributions.",
    link: "https://arxiv.org/pdf/1907.10915.pdf",
    x: 250,
    y: 900,
    color: "#2563eb",
    year: 2019,
    authors: "Y. Ganin, V. Lempitsky",
    venue: "ICML 2019",
    status: "Reading",
    notes: "# SSL Domain Adaptation\n\nShows how pretext tasks like rotation prediction or patch shuffling can align features across domain gaps (e.g. synthetic to real).",
    comments: []
  },
  {
    id: "paper-6",
    title: "Deep Learning Models of AI in CV",
    category: "Optimization",
    summary: "Deep learning models in computer vision face challenges such as high computational resource demands and limited generalization in practical scenarios. To address these issues, this study proposes a systematic optimization framework integrating transfer learning, self-supervised learning, model pruning, and data augmentation. Specifically, transfer learning leverages pre-trained models for efficient feature extraction, while self-supervised learning reduces dependency on labeled data through contrastive pre-training. Model pruning and quantization streamline network complexity, and advanced data augmentation (e.g., Mixup, CutMix) enhances robustness. Experiments across image classification, object detection, and semantic segmentation tasks demonstrate significant improvements: ResNet50 achieved 79.2% classification accuracy, pruned Faster R-CNN reduced parameters by 30% with minimal accuracy loss, and combined self-supervised learning with augmentation boosted semantic segmentation mIoU to 73.4%. These strategies effectively balance accuracy, efficiency, and adaptability, offering practical solutions for resource-constrained applications.",
    link: "https://ieeexplore.ieee.org/document/11071131/",
    x: 700,
    y: 180,
    color: "#059669",
    year: 2025,
    authors: "G. Sharma, K. Rao",
    venue: "IEEE Access",
    status: "Done",
    notes: "# Deep Learning Models of AI in CV\n\nA modern look at combining pruning (removing weights) with data-efficient SSL training. Results show 40% model size reduction with < 1% accuracy drop.",
    comments: []
  },
  {
    id: "paper-7",
    title: "AMP-ViT: Optimizing Vision Transformer Efficiency with Adaptive",
    category: "Optimization",
    summary: "Vision transformers (ViTs) have revolutionized computer vision but face significant challenges due to their high computational and memory demands. Existing post-training quantization methods struggle to maintain performance at low bit-widths due to activation asymmetry and reliance on manual configurations. To overcome these challenges, we introduce SymAlign to address activation asymmetry and reduce clamping loss. Additionally, we propose AutoScale, an automatic and data-driven mechanism that adapts to variant activations. We incorporate the above-mentioned techniques and propose an adaptive mixed-precision posttraining quantization framework for vision transformers (AMP-ViT). Our comprehensive approach addresses asymmetry, variant distribution, and uneven sensitivities, making it the first to tackle these challenges thoroughly. Our experiments on ViT, DeiT, and Swin demonstrate significant accuracy improvements compared with SOTA on the ImageNet dataset. Specifically, our proposed methods achieve accuracy improvements ranging from 0.90% to 23.35% on 4-bit ViTs with single-precision and from 3.82% to 78.14% on 5-bit fully quantized ViTs with mixed-precision.",
    link: "https://openaccess.thecvf.com/content/WACV2025/papers/Tai_AMP-ViT_Optimizing_Vision_Transformer_Efficiency_with_Adaptive_Mixed-Precision_Post-Training_Quantization_WACV_2025_paper.pdf",
    x: 700,
    y: 420,
    color: "#059669",
    year: 2025,
    authors: "X. Liang, J. Song, et al.",
    venue: "IEEE TVCG",
    status: "Reading",
    notes: "# AMP-ViT\n\nFocuses on Adaptive Mixed Precision (AMP) for quantized Vision Transformers. Greatly increases throughput on Edge TPUs during inference.",
    comments: []
  },
  // {
  //   id: "paper-8",
  //   title: "Neural Memory SSM",
  //   category: "Optimization",
  //   summary: "A lightweight gated state-space model that integrates neural memory mechanisms for efficient visual sequence modeling.",
  //   link: "https://ieeexplore.ieee.org/document/10943339/",
  //   x: 700,
  //   y: 660,
  //   color: "#059669",
  //   year: 2025,
  //   authors: "K. Cho, Y. Kim",
  //   venue: "IEEE SPL",
  //   status: "In Review",
  //   notes: "# Neural Memory SSM\n\nCompares State Space Models (SSMs) to traditional Transformers. SSMs scale linearly with sequence length, making them excellent candidates for video representation learning.",
  //   comments: []
  // },
  {
    id: "paper-9",
    title: "Local Masked Reconstruction for Efficient Self-Supervised Learning on High-resolution Images",
    category: "Optimization",
    summary: "Self-supervised learning for computer vision has progressed tremendously and improved many downstream vision tasks, such as image classification, semantic segmentation, and object detection. Among these, generative selfsupervised vision learning approaches, such as MAE and BEiT, show promising performance. However, their global reconstruction mechanism is computationally demanding, especially for high-resolution images. The computational cost increases extensively when scaled to a large-scale dataset. To address this issue, we propose local masked reconstruction (LoMaR), a simple yet effective approach that reconstructs image patches from small neighboring regions. The strategy can be easily integrated into any generative self-supervised learning techniques and improves the trade-off between efficiency and accuracy compared to reconstruction over the entire image. LoMaR is 2.5× faster than MAE and 5.0× faster than BEiT on 384×384 ImageNet pretraining and surpasses them by 0.2% and 0.8% in accuracy, respectively. It is 2.1× faster than MAE on iNaturalist pretraining and gains 0.2% in accuracy. On MS COCO, LoMaR outperforms MAE by 0.5 APbox on object detection and 0.5 APmask on instance segmentation. It also outperforms MAE by 0.2% on semantic segmentation. Our code and pretrained models are available at: https://github.com/junchen14/LoMaR.",
    link: "https://openaccess.thecvf.com/content/WACV2025/papers/Chen_Local_Masked_Reconstruction_for_Efficient_Self-Supervised_Learning_on_High-Resolution_Images_WACV_2025_paper.pdf",
    x: 700,
    y: 900,
    color: "#059669",
    year: 2024,
    authors: "H. Wu, Y. Zhang",
    venue: "IEEE Signal Processing Letters",
    status: "Reading",
    notes: "# Local Masked Reconstruction\n\nOptimizes Masked Autoencoders (MAE). Instead of reconstructing the entire masked image, it reconstructs local high-frequency areas.",
    comments: []
  },
  {
    id: "paper-10",
    title: "An Empirical Study of Training Self-Supervised Vision Transformers",
    category: "Transformer",
    summary: "This paper does not describe a novel method. Instead, it studies a straightforward, incremental, yet must-know baseline given the recent progress in computer vision: self-supervised learning for Vision Transformers (ViT). While the training recipes for standard convolutional networks have been highly mature and robust, the recipes for ViT are yet to be built, especially in the self-supervised scenarios where training becomes more challenging. In this work, we go back to basics and investigate the effects of several fundamental components for training self-supervised ViT. We observe that instability is a major issue that degrades accuracy, and it can be hidden by apparently good results. We reveal that these results are indeed partial failure, and they can be improved when training is made more stable. We benchmark ViT results in MoCo v3 and several other self-supervised frameworks, with ablations in various aspects. We discuss the currently positive evidence as well as challenges and open questions. We hope that this work will provide useful data points and experience for future research.",
    link: "https://openaccess.thecvf.com/content/ICCV2021/papers/Chen_An_Empirical_Study_of_Training_Self-Supervised_Vision_Transformers_ICCV_2021_paper.pdf",
    x: 1200,
    y: 250,
    color: "#dc2626",
    year: 2021,
    authors: "Xinlei Chen, Saining Xie, Kaiming He",
    venue: "ICCV 2021",
    status: "Done",
    notes: "# Empirical Study of SSL ViTs (MoCo v3)\n\nThis paper details MoCo v3 and shows that ViT training under self-supervision can be unstable. They identify that the gradient spike in the first few layers causes instability and propose freezing the patch projection layer.",
    comments: []
  },
  {
    id: "paper-12",
    title: "Neural Memory Self-Supervised State Space Models With Learnable Gates",
    category: "Application",
    summary: "Discrete Ordinary Differential Equations (ODEs) have been employed to develop lightweight deep neural networks in recent years. In this letter, we introduce a novel lightweight UNet variant called the neural memory Self-Supervised State Space Model (nmS4M-UNet) for medical image segmentation, where discrete ODEs serve as the decoder. The proposed nmS4M block has learnable gates and performs multi-head computation to enhance memory updates. Additionally, the nmS4M-UNet incorporates a self-supervised learning branch to improve feature extraction capabilities. The intermediate features are reused as partial input to the decoder, helping to mitigate network overfitting. The nmS4M-UNet reduces the number of parameters by 29.70% compared to the standard UNet. Experimental results on the PH2, ISIC2018, and BU-COCO datasets demonstrate that the proposed nmS4M-UNet achieves performance comparable to state-of-the-art models.",
    link: "https://ieeexplore.ieee.org/document/10887121/",
    x: 1600,
    y: 240,
    color: "#0891b2",
    year: 2024,
    authors: "D. Tan, J. Choi",
    venue: "IEEE T-ITS",
    status: "Done",
    notes: "# Neural Memory Self-Supervised State Space Models With Learnable Gates\n\nSelf-supervised depth and ego-motion estimation. Uses optical flow and photo-consistency loss to guide the training loop.",
    comments: []
  },
  {
    id: "paper-13",
    title: "Perceptual Learning Technology Based on CV and ML",
    category: "Application",
    summary: "To address the issue of low accuracy and poor robustness of perceptual learning in complex scenarios, a new method integrating computer vision and machine learning is adopted, that is, by applying deep neural networks, transfer learning and self-supervised learning, combined with multimodal data fusion strategy, to improve target recognition efficiency and learning ability. First, based on the preprocessing algorithm of improved Gaussian filtering and image segmentation, the quality of image features is improved. Data enhancement methods such as random rotation, flipping, and blurring are used to expand data distribution and improve model adaptability. Secondly, a convolutional neural network (CNN) is utilized in combination with an attention mechanism to extract multi-scale target features, and transfer learning is applied to transfer common features from pre-trained models to reduce dependence on large-scale labeled data. Finally, a contrastive learning framework is constructed to mine the correlation of unlabeled data. Transformer is used to realize the fusion of multimodal data of images and texts, and the model performance is optimized through multi-task learning. The mAP (Mean Average Precision) of the traditional method in dynamic occlusion scenarios is 60.5%, which is relatively weak. This may be because the traditional method cannot fully extract the effective features of the target under the occlusion of complex moving targets. The mAP of the method in this paper is 72.8%, which is higher than that of the traditional method. The perceptual learning method adopted in this paper effectively improves the accuracy and robustness in complex scenarios, and provides reliable technical support for intelligent applications. In the future, it can be combined with edge computing to further optimize the real-time processing capability and promote its application in the fields of unmanned driving and intelligent security.",
    link: "https://ieeexplore.ieee.org/document/10967637",
    x: 1600,
    y: 520,
    color: "#0891b2",
    year: 2024,
    authors: "S. Roy, M. Ali",
    venue: "IEEE Transactions on Cybernetics",
    status: "Done",
    notes: "# Perceptual Learning Technology\n\nCombines vision-language alignment (contrastive) with temporal state-space models. Shows major gains in robotics manipulation benchmarks.",
    comments: []
  }
];

const CONNECTIONS = [
  { from: "paper-root", to: "paper-1" },
  { from: "paper-root", to: "paper-2" },
  { from: "paper-root", to: "paper-3" },
  { from: "paper-root", to: "paper-4" },
  { from: "paper-root", to: "paper-5" },
  { from: "paper-root", to: "paper-6" },
  { from: "paper-root", to: "paper-7" },
  { from: "paper-root", to: "paper-8" },
  { from: "paper-root", to: "paper-9" },
  { from: "paper-root", to: "paper-10" },
  { from: "paper-root", to: "paper-11" },
  { from: "paper-root", to: "paper-12" },
  { from: "paper-root", to: "paper-13" }
];

const TEAM_MEMBERS = [
  { name: "Hitesh", role: "", avatar: "👨‍💻", color: "#3b82f6" }
];

const CATEGORY_COLORS = {
  "Foundations": "#2383e2",
  "Survey": "#9a6dd7",
  "Optimization": "#059669",
  "Transformer": "#e03e3e",
  "Autoencoder": "#d9730d",
  "Application": "#007882",
  "Future": "#ad1a7e"
};

// Expose data to global namespace
window.SPotionData = {
  DEFAULT_PAPERS,
  CONNECTIONS,
  TEAM_MEMBERS,
  CATEGORY_COLORS
};
