// Seed data for SPotion research system
const DEFAULT_PAPERS = [
  {
    id: "paper-root",
    title: "Self-Supervised Learning Foundations",
    category: "Foundations",
    summary: "Core paradigm for representation learning without manual labels. Focuses on learning patterns from data itself.",
    link: "",
    x: 900,
    y: 650,
    color: "#1f4ed8",
    year: 2020,
    authors: "Yann LeCun, Ishan Misra",
    venue: "CACM / Meta AI",
    status: "Done",
    notes: "# Self-Supervised Learning Foundations\n\nSelf-supervised learning (SSL) is the paradigm of training a model on a pretext task where the targets are generated automatically from the data. This allows using massive datasets without requiring human annotation.\n\n### Key Concepts\n- **Joint Embedding Architectures**: Map inputs to representations without generating pixels directly.\n- **Contrastive Learning**: Pull representations of similar views together while pushing dissimilar views apart.\n- **Non-contrastive/Regularized Methods**: Avoid collapse using variance/covariance constraints (e.g., VICReg, Barlow Twins).",
    comments: []
  },
  {
    id: "paper-1",
    title: "Recent Advancements in SSL Paradigms",
    category: "Survey",
    summary: "Comprehensive survey of recent SSL methods, architectures, pretext tasks, and open problems in CV and NLP.",
    link: "https://arxiv.org/pdf/2405.02171.pdf",
    x: 250,
    y: 180,
    color: "#7c3aed",
    year: 2024,
    authors: "A. Zhang, B. Xu, et al.",
    venue: "arXiv (2405)",
    status: "Reading",
    notes: "# Recent Advancements in SSL Paradigms\n\nThis survey paper organizes SSL methods into contrastive, generative, and predictive approaches. It provides a comprehensive analysis of taxonomy and performance benchmarks.",
    comments: []
  },
  {
    id: "paper-2",
    title: "SSL: Algorithms, Applications & Future Trends",
    category: "Survey",
    summary: "A detailed map of SSL algorithms, application domains, and emerging future trends in generative vision models.",
    link: "https://arxiv.org/pdf/2408.17059.pdf",
    x: 250,
    y: 360,
    color: "#7c3aed",
    year: 2024,
    authors: "S. Liu, T. Wang, et al.",
    venue: "arXiv (2408)",
    status: "In Review",
    notes: "# SSL: Algorithms, Applications & Future Trends\n\nExcellent reading for understanding current industry applications (autonomous driving, healthcare, robotics) and challenges like multimodal alignment.",
    comments: []
  },
  {
    id: "paper-3",
    title: "JEPA (Joint-Embedding Predictive Architecture)",
    category: "Foundations",
    summary: "Yann LeCun's proposal for visual world models learning representations by predicting abstract representations of parts of an image.",
    link: "https://arxiv.org/pdf/2301.08243.pdf",
    x: 250,
    y: 540,
    color: "#2563eb",
    year: 2023,
    authors: "Yann LeCun",
    venue: "arXiv / Meta AI",
    status: "Done",
    notes: "# Joint-Embedding Predictive Architecture (JEPA)\n\nJEPA avoids predicting raw pixel content (which contains too much noise/unpredictable detail) and instead predicts representations in a joint-embedding space.\n\n### Advantages:\n1. Less computationally expensive than autoencoders.\n2. Captures semantic relationships better.\n3. Robust to pixel-level variations.",
    comments: []
  },
  {
    id: "paper-4",
    title: "Arbitrary Scenarios SSL",
    category: "Foundations",
    summary: "Generalized SSL representations designed to capture features robust to domain shift and arbitrary environment variations.",
    link: "https://arxiv.org/pdf/2210.03289.pdf",
    x: 250,
    y: 720,
    color: "#2563eb",
    year: 2022,
    authors: "R. Devry, M. Patel",
    venue: "NeurIPS 2022",
    status: "Bookmarked",
    notes: "# Arbitrary Scenarios SSL\n\nExplores generalizability of SSL models to unseen tasks and out-of-distribution (OOD) scenarios. Crucial for robust robotics applications.",
    comments: []
  },
  {
    id: "paper-5",
    title: "SSL Domain Adaptation",
    category: "Foundations",
    summary: "Cross-domain representation learning techniques utilizing self-supervision to align source and target distributions.",
    link: "https://arxiv.org/pdf/1907.10915.pdf",
    x: 250,
    y: 900,
    color: "#2563eb",
    year: 2019,
    authors: "Y. Ganin, V. Lempitsky",
    venue: "ICML 2019",
    status: "Done",
    notes: "# SSL Domain Adaptation\n\nShows how pretext tasks like rotation prediction or patch shuffling can align features across domain gaps (e.g. synthetic to real).",
    comments: []
  },
  {
    id: "paper-6",
    title: "Deep Learning Models of AI in CV",
    category: "Optimization",
    summary: "Investigates the synergy between transfer learning, network pruning, and data augmentation in deep SSL vision models.",
    link: "https://ieeexplore.ieee.org/document/11071131/",
    x: 700,
    y: 180,
    color: "#059669",
    year: 2025,
    authors: "G. Sharma, K. Rao",
    venue: "IEEE Access",
    status: "Reading",
    notes: "# Deep Learning Models of AI in CV\n\nA modern look at combining pruning (removing weights) with data-efficient SSL training. Results show 40% model size reduction with < 1% accuracy drop.",
    comments: []
  },
  {
    id: "paper-7",
    title: "AMP-ViT",
    category: "Optimization",
    summary: "Mixed-precision quantization framework designed for Vision Transformers training under SSL constraints.",
    link: "https://openaccess.thecvf.com/content/WACV2025/papers/Tai_AMP-ViT_Optimizing_Vision_Transformer_Efficiency_with_Adaptive_Mixed-Precision_Post-Training_Quantization_WACV_2025_paper.pdf",
    x: 700,
    y: 420,
    color: "#059669",
    year: 2025,
    authors: "X. Liang, J. Song, et al.",
    venue: "IEEE TVCG",
    status: "Reading",
    notes: "# AMP-ViT\n\nFocuses on Adaptive Mixed Precision (AMP) for quantized Vision Transformers. Greatly increases throughput on Edge TPUs during inference.",
    comments: []
  },
  {
    id: "paper-8",
    title: "Neural Memory SSM",
    category: "Optimization",
    summary: "A lightweight gated state-space model that integrates neural memory mechanisms for efficient visual sequence modeling.",
    link: "https://ieeexplore.ieee.org/document/10943339/",
    x: 700,
    y: 660,
    color: "#059669",
    year: 2025,
    authors: "K. Cho, Y. Kim",
    venue: "IEEE SPL",
    status: "In Review",
    notes: "# Neural Memory SSM\n\nCompares State Space Models (SSMs) to traditional Transformers. SSMs scale linearly with sequence length, making them excellent candidates for video representation learning.",
    comments: []
  },
  {
    id: "paper-9",
    title: "Local Masked Reconstruction",
    category: "Optimization",
    summary: "Highly efficient masked image reconstruction strategy that minimizes compute by localizing patches inside attention zones.",
    link: "https://openaccess.thecvf.com/content/WACV2025/papers/Chen_Local_Masked_Reconstruction_for_Efficient_Self-Supervised_Learning_on_High-Resolution_Images_WACV_2025_paper.pdf",
    x: 700,
    y: 900,
    color: "#059669",
    year: 2024,
    authors: "H. Wu, Y. Zhang",
    venue: "IEEE Signal Processing Letters",
    status: "Bookmarked",
    notes: "# Local Masked Reconstruction\n\nOptimizes Masked Autoencoders (MAE). Instead of reconstructing the entire masked image, it reconstructs local high-frequency areas.",
    comments: []
  },
  {
    id: "paper-10",
    title: "Empirical Study of SSL ViTs",
    category: "Transformer",
    summary: "In-depth empirical investigation analyzing the training stability, hyperparameters, and collapse modes of SSL-trained ViTs.",
    link: "https://openaccess.thecvf.com/content/ICCV2021/papers/Chen_An_Empirical_Study_of_Training_Self-Supervised_Vision_Transformers_ICCV_2021_paper.pdf",
    x: 1200,
    y: 250,
    color: "#dc2626",
    year: 2021,
    authors: "Xinlei Chen, Saining Xie, Kaiming He",
    venue: "ICCV 2021",
    status: "Done",
    notes: "# Empirical Study of SSL ViTs (MoCo v3)\n\nThis paper details MoCo v3 and shows that ViT training under self-supervision can be unstable. They identify that the gradient spike in the first few layers causes instability and propose freezing the patch projection layer.",
    comments: []
  },
  {
    id: "paper-11",
    title: "Point-UMAE",
    category: "Autoencoder",
    summary: "Unsupervised masked autoencoder framework designed for 3D point cloud representations, showing high transferability.",
    link: "https://ieeexplore.ieee.org/document/10967637/",
    x: 1200,
    y: 520,
    color: "#ea580c",
    year: 2025,
    authors: "Z. Liang, L. Wang",
    venue: "IEEE T-IP",
    status: "In Review",
    notes: "# Point-UMAE\n\nExtension of MAE to 3D point cloud data. Uses a point shifting strategy to represent irregular geometry before masking.",
    comments: []
  },
  {
    id: "paper-12",
    title: "Visual Odometry via SSL",
    category: "Application",
    summary: "End-to-end self-supervised visual odometry utilizing scene appearance-structure fusion for localization.",
    link: "https://ieeexplore.ieee.org/document/10887121/",
    x: 1600,
    y: 240,
    color: "#0891b2",
    year: 2024,
    authors: "D. Tan, J. Choi",
    venue: "IEEE T-ITS",
    status: "Bookmarked",
    notes: "# Visual Odometry via SSL\n\nSelf-supervised depth and ego-motion estimation. Uses optical flow and photo-consistency loss to guide the training loop.",
    comments: []
  },
  {
    id: "paper-13",
    title: "Perceptual Learning Technology",
    category: "Application",
    summary: "Integrates attention mechanisms and multimodal SSL fusion for advanced perceptual processing in autonomous agents.",
    link: "https://ieeexplore.ieee.org/document/10405055/",
    x: 1600,
    y: 520,
    color: "#0891b2",
    year: 2024,
    authors: "S. Roy, M. Ali",
    venue: "IEEE Transactions on Cybernetics",
    status: "Reading",
    notes: "# Perceptual Learning Technology\n\nCombines vision-language alignment (contrastive) with temporal state-space models. Shows major gains in robotics manipulation benchmarks.",
    comments: []
  },
  {
    id: "paper-14",
    title: "Edge AI Deployment",
    category: "Future",
    summary: "Investigating lightweight distillation of massive SSL foundations models to low-power edge platforms.",
    link: "",
    x: 1600,
    y: 860,
    color: "#9333ea",
    year: 2025,
    authors: "F. Neri, G. Gomez",
    venue: "EdgeAI Conference 2025",
    status: "Reading",
    notes: "# Edge AI Deployment\n\nFuture research roadmap about moving SSL visual models to sub-watt microcontrollers. Looks at binary neural networks and sparse activations.",
    comments: []
  },
  {
    id: "paper-15",
    title: "Medical Imaging SSL",
    category: "Future",
    summary: "Leveraging self-supervised pretraining on generic medical datasets to adapt to low-label diagnostic tasks.",
    link: "",
    x: 1850,
    y: 1030,
    color: "#9333ea",
    year: 2024,
    authors: "M. Ghafoorian, H. Karssemeijer",
    venue: "Medical Image Analysis",
    status: "Bookmarked",
    notes: "# Medical Imaging SSL\n\nPre-training on 10 million unlabeled clinical scans, showing state-of-the-art results on tumor segmentation with just 1% labeled tuning.",
    comments: []
  },
  {
    id: "paper-16",
    title: "Robotics SSL Perception",
    category: "Future",
    summary: "Autonomous perception learning for robotic manipulation and navigation utilizing multi-view contrastive video SSL.",
    link: "",
    x: 1850,
    y: 1230,
    color: "#9333ea",
    year: 2025,
    authors: "P. Agrawal, S. Levine",
    venue: "CoRL 2025",
    status: "In Review",
    notes: "# Robotics SSL Perception\n\nUsing robot's own interaction data (self-touch, visual change) as self-supervised signals. Bridges the simulation-to-real gap rapidly.",
    comments: []
  }
];

const CONNECTIONS = [
  { from: "paper-root", to: "paper-1" },
  { from: "paper-root", to: "paper-2" },
  { from: "paper-root", to: "paper-3" },
  { from: "paper-root", to: "paper-4" },
  { from: "paper-root", to: "paper-5" },
  { from: "paper-root", to: "paper-6" },
  { from: "paper-root", to: "paper-7" },
  { from: "paper-root", to: "paper-8" },
  { from: "paper-root", to: "paper-9" },
  { from: "paper-root", to: "paper-10" },
  { from: "paper-root", to: "paper-11" },
  { from: "paper-root", to: "paper-12" },
  { from: "paper-root", to: "paper-13" },
  { from: "paper-root", to: "paper-14" },
  { from: "paper-root", to: "paper-15" },
  { from: "paper-root", to: "paper-16" }
];

const TEAM_MEMBERS = [
  { name: "Hitesh", role: "", avatar: "👨‍💻", color: "#3b82f6" }
];

const CATEGORY_COLORS = {
  "Foundations": "#2383e2",
  "Survey": "#9a6dd7",
  "Optimization": "#059669",
  "Transformer": "#e03e3e",
  "Autoencoder": "#d9730d",
  "Application": "#007882",
  "Future": "#ad1a7e"
};

// Expose data to global namespace
window.SPotionData = {
  DEFAULT_PAPERS,
  CONNECTIONS,
  TEAM_MEMBERS,
  CATEGORY_COLORS
};
